name: VinkamiLang
version: '${project.version}'
main: com.vinkami.vinkamilang.VinkamiLang
api-version: 1.18
description: vinkami's scripting language for easy scripting!
commands:
  vk:
    description: Commands for vinkamilang
    usage: /vk <command>
